spring:
  data:
    mongodb:
      database: switter
      host: localhost
      port: 27017
      password: qwerty12345
      username: admin
      authentication-database: admin

switter:
  app:
    jwtSecret: switterjavasecretkeyswitterjavasecretkeyswitterjavasecretkey
    jwtExpiration: 1800

